### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Kenneth-Wong** [aim-uofa/FreeCustom#1]
Nice works! Hope the code released as soon as possible!

**Comment by hecoding** [comment]
Hi, it's been 3 months. Any progress?

Thanks!

**Comment by wzic** [comment]
Hi, any progress ?

**Comment by dingangui** [comment]
Sorry to keep you waiting for so long, we have just released the initial version of the code.

**Comment by wzic** [comment]
Thanks!
