### ISSUE TITLE
What is style fidelity ?

### ISSUE THREAD

**Issue by wzic** [aim-uofa/FreeCustom#2]
Hi!
May I know what is style fidelity ? How much influence does it have on the result ? It seems that this concept is not mentioned in the paper. Thanks.

**Comment by dingangui** [comment]
style fidelity is a concept occurred in controlnet reference only, see here: https://github.com/Mikubill/sd-webui-controlnet/discussions/1236. In our settings, we set style fidelity=1.0 to get the most consistent results.

**Comment by wzic** [comment]
Thanks
